name: coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Run tests
        run: |
          go test ./... -covermode=count -coverpkg=./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
          COV=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | tr -d '%')
          printf '{"totals": {"percent_covered_display": %.2f}}' "$COV" > coverage.json

      - name: Update coverage badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@v1.0.1

